name: app_models
description: App models package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  realm: ^3.1.0

dev_dependencies:
  very_good_analysis: ^5.0.0
