# global_options:
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
      realm:realm_generator:
        enabled: true
        generate_for: 
          exclude:
            - lib/**.dart
          include:
            #- packages/**.dart
            - packages-app/app_models/**.dart
            - packages-app/app_data/**.dart
      freezed|freezed:
        enabled: true
        generate_for:
          include:
            - lib/**_mixin.dart
            - lib/**_provider.dart
            - lib/**_event.dart
            - lib/**_state.dart
            - lib/**_failures.dart
          exclude:
            - packages/**.dart
            - packages-app/**.dart
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.freezed.dart'
      riverpod:
        generate_for:
          include:
            - lib/**_provider.dart
          exclude:
            - lib/**_routes.dart
            - packages/**.dart
            - packages-app/**.dart
      go_router_builder:
        generate_for:
          - lib/**_routes.dart
