# global_options:
targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      source_gen|combining_builder:
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.g.dart'
      freezed|freezed:
        enabled: true
        generate_for:
          include:
            - lib/**_mixin.dart
            - lib/**_provider.dart
            - lib/**_event.dart
            - lib/**_state.dart
          exclude:
            - packages/**.dart
        options:
          build_extensions:
            '^lib/{{}}.dart': 'lib/generated/{{}}.freezed.dart'
      riverpod:
        generate_for:
          include:
            - lib/**_provider.dart
          exclude:
            - lib/**_routes.dart
      go_router_builder:
        generate_for:
          - lib/**_routes.dart
      
# builders:
#   go_router_builder:
#     runs_after:
#       - freezed: freezed_generator
#       - riverpod: riverpod_generator     