name: mycaselog
description: "my log of surgeries"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Generic Packages
  async_result:
    path: packages/async_result
  authentication_client:
    path: packages/authentication_client
  encryption_client:
    path: packages/encryption_client
  logger_client:
    path: packages/logger_client
  state_of:
    path: packages/state_of
  storage:
    path: packages/storage

  # App packages
  app_annotations:
    path: packages-app/app_annotations
  app_assets: 
    path: packages-app/app_assets
  app_extensions:
    path: packages-app/app_extensions
  app_l10n:
    path: packages-app/app_l10n
  app_models:
    path: packages-app/app_models
  app_ui:
    path: packages-app/app_ui
  app_data:
    path: packages-app/app_data
  label_ocr:
    path: packages-app/label_ocr
  media_manager:
    path: packages-app/media_manager
  misc_packages:
    path: packages-app/misc_packages

  # pub packages
  animations: ^2.0.11
  async: ^2.11.0
  collection: 1.18.0
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1
  go_router: ^14.2.0
  realm: ^3.0.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^3.0.0-dev.3
  intl: ^0.19.0
  riverpod_annotation: ^3.0.0-dev.3
  reactive_forms: ^17.0.1
  recase: ^4.1.0
  shared_preferences: ^2.2.3
  google_sign_in: ^6.2.1
  flow_builder: ^0.1.0
  intl_utils: ^2.8.7
  flutter_svg: ^2.0.10+1
  #firebase_analytics: 10.10.4
  firebase_auth_platform_interface: 7.2.5
  firebase_auth: 4.19.4
  firebase_core: 2.30.1
  firebase_crashlytics: 3.5.4
  #firebase_messaging: 14.9.1
  firebase_ui_auth: ^1.14.0
  cloud_firestore: ^4.17.2
  firebase_storage: 11.7.4
  flutter_adaptive_scaffold: ^0.1.11+1
  json_annotation: ^4.9.0
  share_plus: ^9.0.0
  local_auth: ^2.2.0
  image_picker: ^1.1.2
  
dev_dependencies: 
  build_runner: ^2.4.11
  freezed: ^2.5.3
  flutter_launcher_icons: ^0.13.1
  go_router_builder: ^2.7.0
  pubspec_dependency_sorter: ^1.0.4
  riverpod_generator: ^3.0.0-dev.11
  very_good_analysis: ^5.1.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
