name: app_assets
description: App assets package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/onboarding/
    - assets/logo/

# dart pub global activate flutter_gen
# dart run build_runner build
flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
  output: lib/
  line_length: 80
  integrations:
    flutter_svg: true
