name: app_repositories
description: App repositories package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  connectivity_plus: ^6.0.3
  flutter:
    sdk: flutter
  realm: ^3.2.0
  cloud_firestore: ^4.17.2
  firebase_storage: 11.7.4
  shared_preferences: ^2.2.3
  flutter_cache_manager: ^3.3.2
  path: ^1.9.0
  path_provider: ^2.1.3
  # App Packages
  app_annotations:  
    path: ../app_annotations
  app_extensions:
    path: ../app_extensions
  app_models: 
    path: ../app_models
  # packages
  authentication_client:
    path: ../../packages/authentication_client
  encryption_client:
    path: ../../packages/encryption_client
  logger_client: 
    path: ../../packages/logger_client
  collection: ^1.18.0

dev_dependencies:
  very_good_analysis: ^5.0.0
