name: upload_flow_manager
description: A UI Package for manageing upload flow
version: 0.0.3
homepage: https://www.cloudonlanapps.com

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6 
  collection: ^1.17.1

  material_design_icons_flutter: ^7.0.7296
  path: ^1.8.3
  path_provider: ^2.1.0
  percent_indicator: ^4.2.3
  progress_indicators: ^1.0.0  
  sqlite3: ^2.1.0
  sqlite3_flutter_libs: ^0.5.15
  adaptive_dialog: ^1.9.0
  image_picker: ^1.0.4
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

