name: label_ocr
description: Label ocr package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  app_models: 
    path: ../app_models
  app_extensions:
    path: ../app_extensions
  camera: ^0.11.0
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.7.1
  google_mlkit_text_recognition: ^0.13.0
  permission_handler: ^11.3.1

dev_dependencies:
  very_good_analysis: ^6.0.0
