name: authentication_client
description: Authentication client package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  equatable: ^2.0.5
  firebase_auth: 4.19.4
  firebase_crashlytics: 3.5.4
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.2.1
  #realm: ^3.0.0
  storage:
    path: '../storage'

dev_dependencies:
  build_runner: ^2.4.9
  freezed: ^2.5.2
  very_good_analysis: ^6.0.0
