name: exampe
description: upload_flow_manager usage example
publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  upload_flow_manager:  
    path: ../
  http: ^1.1.0
  flutter_riverpod: ^2.3.10
  image_picker: ^1.0.2
  sqlite3: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
