// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQKt3c2t5krXqgERGd51LF_VgWbbjRsME',
    appId: '1:575010129050:android:e3093448048f1960250b23',
    messagingSenderId: '575010129050',
    projectId: 'mycaselog-dev',
    storageBucket: 'mycaselog-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnRrxfz8TEm3xEFrWok4WVza_EtYj2DN8',
    appId: '1:575010129050:ios:f85f8a54bbf6cd27250b23',
    messagingSenderId: '575010129050',
    projectId: 'mycaselog-dev',
    storageBucket: 'mycaselog-dev.appspot.com',
    androidClientId: '575010129050-591jpb83rmphh1i592rjfq9hc26dmlii.apps.googleusercontent.com',
    iosClientId: '575010129050-v9hcf364sk7bs7vvl9ojofuol9bak7qq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mycaselog',
  );

}