// // This file is "model.dart"
// import 'package:dart_mappable/dart_mappable.dart';

// import 'package:realm/realm.dart';

// import '../model_utils.dart';

// //part 'media_model.g.dart';
// part 'media_realm.realm.dart';
// // Will be generated by dart_mappable
// part 'media_realm.mapper.dart';

// ///Media status
// enum MediaStatus {
//   cancelled,
//   failed,
//   processing,
//   queued,
//   removed,
//   success,
//   uploading,
// }

// @RealmModel()
// @MappableClass()
// class _MediaRealm with _MediaRealmMappable {
//   @PrimaryKey()
//   late String mediaID;
//   late String authorID;
//   late String? fileType;
//   late String? fileName;
//   late String? fileUri;
//   late String? mediumUri;
//   late String? thumbUri;
//   @Indexed()
//   late String? caseID;
//   @MapTo('status')
//   late String? _status;
//   @Ignored()
//   MediaStatus get status {
//     return MediaStatus.values.byName(_status ?? MediaStatus.queued.name);
//   }

//   @Ignored()
//   set status(MediaStatus value) => _status = value.name;

//   @Indexed(RealmIndexType.fullText)
//   late String? comment;
//   @Indexed()
//   late int removed = 0;
//   late int createdAt = 0;
//   late int timestamp = 0;

//   MediaRealm toRealmObject() {
//     return MediaRealm(
//       mediaID,
//       authorID,
//       fileType: fileType,
//       fileName: fileName,
//       fileUri: fileUri,
//       mediumUri: mediumUri,
//       thumbUri: thumbUri,
//       caseID: caseID,
//       status: _status,
//       comment: comment,
//       removed: removed,
//       createdAt: createdAt,
//       timestamp: timestamp,
//     );
//   }

//   static MediaRealm fromJson(Map<String, dynamic> json) =>
//       MediaRealmX.fromJson(json);

//   Map<String, dynamic> toJson() => _$MediaRealmToJson(this);
// }

// extension MediaRealmX on MediaRealm {
//   static MediaRealm fromJson(Map<String, dynamic> json) =>
//       _$MediaRealmFromJson(json).toRealmObject();

//   Map<String, dynamic> toJson() => _$MediaRealmToJson(this);

//   static MediaRealm zero(String authorID) {
//     final timestamp = ModelUtils.getTimestamp;

//     final mediaRealm = MediaRealm(
//       ModelUtils.uniqueID,
//       authorID,
//       createdAt: timestamp,
//       timestamp: timestamp,
//     );

//     return mediaRealm;
//   }
// }
