include: package:very_good_analysis/analysis_options.4.0.0.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    constant_identifier_names: true
    prefer_relative_imports: true
    always_use_package_imports: false
    public_member_api_docs: false

analyzer:
  errors:
    invalid_annotation_target: ignore
    mixin_inherits_from_not_object: ignore
    mixin_with_non_class_superclass: ignore
  language:
    strict-raw-types: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gform.dart"
