name: media_manager
description: Media manager package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Normal packages
  path: ^1.9.0
  image_picker: ^1.1.1
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.3
  flutter_cache_manager:  ^3.3.2
  firebase_storage: ^11.7.4
  mime_type: ^1.0.0
  collection: ^1.18.0
  async: ^2.11.0
  app_annotations:
    path: ../app_annotations
  app_models:
    path: ../app_models
  app_l10n:
    path: ../app_l10n
  logger_client:
    path: ../../packages/logger_client

dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  very_good_analysis: ^6.0.0