name: app_data
description: App data package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # App Packages
  app_annotations:  
    path: ../app_annotations
  app_extensions:
    path: ../app_extensions
  app_models: 
    path: ../app_models
  # packages
  authentication_client:
    path: ../../packages/authentication_client
  encryption_client:
    path: ../../packages/encryption_client
  logger_client: 
    path: ../../packages/logger_client
  connectivity_plus: ^6.0.5
  cloud_firestore: ^5.2.1
  collection: ^1.18.0
  firebase_storage: 12.1.3
  flutter_cache_manager: ^3.4.0
  path_provider: ^2.1.4
  path: ^1.9.0
  realm: ^3.4.1
  shared_preferences: ^2.3.1
  

dev_dependencies:
  very_good_analysis: ^6.0.0
