name: app_data
description: App data package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # App Packages
  app_annotations:  
    path: ../app_annotations
  app_extensions:
    path: ../app_extensions
  app_models: 
    path: ../app_models

  # packages
  authentication_client:
    path: ../../packages/authentication_client
  encryption_client:
    path: ../../packages/encryption_client
  logger_client: 
    path: ../../packages/logger_client
  async_result:
    path: ../../packages/async_result
  storage:
    path: ../../packages/storage
  
  cloud_firestore: ^4.17.2
  realm: ^3.1.0
  firebase_storage: 11.7.4
  shared_preferences: ^2.2.3
  freezed_annotation: ^2.4.1
  flutter_cache_manager: ^3.3.2
  flutter_image_compress: ^2.3.0
  mime_type: ^1.0.0
  path: ^1.9.0
  path_provider: ^2.1.3

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.4.1
  very_good_analysis: ^6.0.0
