name: misc_packages
description: Misc packages package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  app_extensions:
    path: ../app_extensions
  app_l10n:
    path: ../app_l10n
  app_models:
    path: ../app_models
  logger_client:
    path: ../../packages/logger_client
  animations: ^2.0.11
  reactive_forms: ^17.0.1
  recase: ^4.1.0
  intl: ^0.19.0

dev_dependencies:
  freezed: ^2.5.4
  very_good_analysis: ^6.0.0
