name: state_of
description: State of package.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.2

dev_dependencies:
  build_runner: 2.4.9
  freezed: ^2.5.3
  very_good_analysis: ^6.0.0
